apiVersion: apps/v1
kind: Deployment
metadata:
  name: process order
  labels:
    app: process order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process order
  template:
    metadata:
      labels:
        app: process order
    spec:
      containers:
        - name: process order
          image: "username/process order:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
